FROM nginx:1.20.1
MAINTAINER zss <zss@cetiti.com>
RUN mkdir /usr/share/nginx/html/screen
COPY screen/ /usr/share/nginx/html/screen/

#设置时区
RUN ln -snf /usr/share/zoneinfo/Asia/Shanghai /etc/localtime && echo 'Asia/Shanghai' >/etc/timezone

RUN rm /etc/nginx/nginx.conf
ADD nginx.conf /etc/nginx
